all:
  hosts:
    vm-devsecops:
      ansible_host: 4.168.238.158
      ansible_user: azureadmin
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_azure
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    ansible_python_interpreter: /usr/bin/python3
